### ISSUE TITLE
Multiline patterns missing (eg. ruby + python)

### ISSUE THREAD

**Issue by haroldtreen** [nknapp/comment-patterns#2]
Really cool library @nknapp !

I was looking through the languages and noticed some don't have multiline patterns (eg. ruby and python). 

https://github.com/nknapp/comment-patterns/blob/master/languages/patterns/ruby.js
https://github.com/nknapp/comment-patterns/blob/master/languages/patterns/python.js

Is there a reason these were omitted? Would it be easy to add?

Trying to use `multilang-extract-comments` to pull block comments from a variety of languages and it is relying on these patterns.

Thanks!

**Comment by nknapp** [comment]
I have extracted the pattern from the `groc'-project. The reason is probably that it wasn't in there when I did that (and that I use neither Ruby nor Python myself. Feel free to make a PR with to include the missing patterns.

**Comment by haroldtreen** [comment]
Ah, gotcha. I'll give it a go and submit a PR once it's figured out :).

**Comment by nknapp** [comment]
I just found this about Python: http://stackoverflow.com/questions/7696924/multiline-comments-in-python
`'''` are just multiline-strings. Is there the danger of finding false-positives? Is there a way to identify apidoc-comments? Could you write a test verifying that the .regex-function correctly identifies comments?

As for ruby: http://stackoverflow.com/questions/2989762/multi-line-comments-in-ruby says that the delimiters must be at the beginning of the line. Should be an anchored regex rather than a string then.

**Comment by nknapp** [comment]
I should mention. I actually have almost given up on this project, because the mainly attempted use-case (https://github.com/nknapp/multilang-apidocs) was harder to achieve than I thought. I have given up on creating a generic api-doc generator for all possible programming languages.

If you are actively using it, I should probably add you as a collaborator on github and npm so that I don't hav e to publish your changes myself...

**Comment by haroldtreen** [comment]
Hey @nknapp 

That would be great! I'll look into your question and look at adding a test. I have a test in my own project and these changes have gotten the comments to extract 👍 .

Thanks!

**Comment by haroldtreen** [comment]
Added tests for Python and Ruby:
https://github.com/nknapp/comment-patterns/pull/3/commits/76f22f85664875e267432bbd1c47cef50d48b666

I tried making the Ruby regex contain a `(\n|^)` so that it would look for things at the start of the line. But it seems these patterns get built into a larger pattern. The resulting regex wouldn't match anything.

I'm not worried about this though. People will likely run into problems with running their ruby code before they run into errors where this is outputting comments that don't exist. 

![image](https://cloud.githubusercontent.com/assets/1745854/17822362/934f05f0-660b-11e6-9a0d-76de7b220bc5.png)

Python test has a case where there's a multi-line string in a variable declaration. No issues. 

Not sure about apidoc detection, but not really worried about that for our use case.

So this should be ready to go!

Not sure if you wanted to add me as an npm publisher, but if so this is my profile: https://www.npmjs.com/~haroldtreen

Looks like publishing a patch for this will get picked up by the other module and get things working :). I guess I can merge it but I'll leave it for a bit in case you have other thoughts.

Thanks @nknapp !

**Comment by nknapp** [comment]
I have added you as npm publisher. 

Before you publish

* be sure to update the CHANGELOG.md before publishing (0.9.0)
* use the "squash-merge"-function of Github to merge your PR.

I haven't written any docs for the release-process yet. But I have always used the [release-tools](https://www.npmjs.com/package/release-tools).

Let me know if you have any problems.

**Comment by haroldtreen** [comment]
Awesome! I'll get this merged now. 

Thanks 😃!
