### ISSUE TITLE
PHP support for multiline comments

### ISSUE THREAD

**Issue by seancsnyder** [nknapp/comment-patterns#6]
I already have a pull request for this, but the current code does not support multiline comments for PHP.

https://github.com/nknapp/comment-patterns/pull/5

**Comment by nknapp** [comment]
Hi Sean, sorry for the delay. I am otherwise occupied right now. But I found the time to merge your request and publish a new version.

That said, I'm not using this project myself anymore. But if anyone volunteers to take over and merges requests like this, just say a word and I'll add you as collaborator and as owner on npm.

**Comment by seancsnyder** [comment]
Much appreciated! You can add me for the time being unless anyone else is interested
